name: "Lint and Test Code"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main  # run build-image action for main
  pull_request:

jobs:
  lint:
    uses: .github/workflows/run-linting.yml
    secrets: inherit

  test:
    uses: .github/workflows/run-tests.yml
    secrets: inherit
#    needs: lint
