name: Run Tests

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
          required: true
      DOCKER_PASSWORD:
          required: true

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: spaneng/doover_device_base
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pipenv, Pipfile packages, pytest and pytest-cov
        run: |
          apt update && apt install -y git
          pip install pipenv pytest pytest-cov pytest-asyncio
          pipenv install --dev --ignore-pipfile --deploy --ignore-installed --no-cache-dir        

      - name: Run tests
        run: |
          pipenv run pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
